import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';

export type DroppedItemDocument = DroppedItem & Document;

@Schema({ timestamps: true })
export class DroppedItem {
  /** Unique GUID generated by the game client (Master). */
  @Prop({ required: true, unique: true })
  dropId: string;

  /** Photon room name where the item was dropped. */
  @Prop({ required: true })
  roomName: string;

  // ── Item Snapshot ──────────────────────────────────────────

  @Prop({ required: true })
  itemId: string;

  @Prop({ required: true })
  itemName: string;

  @Prop({ required: true })
  itemType: number;

  @Prop({ required: true })
  itemCategory: number;

  @Prop({ default: 0 })
  quality: number;

  @Prop({ default: 1 })
  quantity: number;

  @Prop({ default: '' })
  iconUrl: string;

  @Prop({ default: true })
  isStackable: boolean;

  // ── World Position ─────────────────────────────────────────

  @Prop({ required: true })
  worldX: number;

  @Prop({ required: true })
  worldY: number;

  // ── Chunk Coordinates ──────────────────────────────────────

  @Prop({ required: true })
  chunkX: number;

  @Prop({ required: true })
  chunkY: number;

  // ── Section ────────────────────────────────────────────────

  @Prop({ default: 0 })
  sectionId: number;

  // ── Ownership / Timing ─────────────────────────────────────

  /** Photon ActorNumber of the player who dropped the item. */
  @Prop({ default: 0 })
  droppedByActorId: number;

  /** UTC timestamp when the item was dropped. */
  @Prop({ type: Date })
  droppedAt: Date;

  /**
   * UTC timestamp when the item should auto-despawn.
   * MongoDB TTL index will automatically remove expired documents.
   */
  @Prop({ type: Date })
  expireAt: Date;
}

export const DroppedItemSchema = SchemaFactory.createForClass(DroppedItem);

// TTL index: MongoDB automatically deletes documents when expireAt <= now
DroppedItemSchema.index({ expireAt: 1 }, { expireAfterSeconds: 0 });

// Compound index for efficient chunk-based queries
DroppedItemSchema.index({ roomName: 1, chunkX: 1, chunkY: 1 });

// Fast lookup by dropId (already unique via @Prop, but explicit index helps)
DroppedItemSchema.index({ dropId: 1 });
