using System;

/// <summary>
/// Plain C# model representing a dropped item in the world.
/// Fully JSON-serializable for API transport and Photon binary serialization.
/// </summary>
[Serializable]
public class DroppedItemData
{
    // ── Identity ──────────────────────────────────────────────
    /// <summary>Unique identifier (GUID) generated by Master client on drop.</summary>
    public string dropId;

    /// <summary>Photon room name where this item was dropped.</summary>
    public string roomName;

    // ── Item Snapshot (copied from ItemData at drop time) ─────
    public string       itemId;
    public string       itemName;
    public ItemType     itemType;
    public ItemCategory itemCategory;
    public Quality      quality;
    public int          quantity;
    public string       iconUrl;
    public bool         isStackable;

    // ── World Position ────────────────────────────────────────
    public float worldX;
    public float worldY;

    // ── Chunk Coordinates (for chunk-based loading) ───────────
    public int chunkX;
    public int chunkY;

    // ── Section ───────────────────────────────────────────────
    public int sectionId;

    // ── Ownership / Timing ────────────────────────────────────
    /// <summary>Photon ActorNumber of the player who dropped the item.</summary>
    public int droppedByActorId;

    /// <summary>UTC timestamp when the item was dropped.</summary>
    public string droppedAt;

    /// <summary>UTC timestamp when the item should auto-despawn (droppedAt + 360s).</summary>
    public string expireAt;

    // ── Helper Properties (not serialized) ────────────────────

    /// <summary>Seconds remaining before this item despawns.</summary>
    public double RemainingSeconds
    {
        get
        {
            if (DateTime.TryParse(expireAt, null, System.Globalization.DateTimeStyles.RoundtripKind, out DateTime expire))
            {
                return (expire - DateTime.UtcNow).TotalSeconds;
            }
            return 0;
        }
    }

    /// <summary>True when the item should start blinking (last 30 seconds).</summary>
    public bool ShouldBlink => RemainingSeconds <= 30.0 && RemainingSeconds > 0;

    /// <summary>True when the item has expired.</summary>
    public bool IsExpired => RemainingSeconds <= 0;

    // ── Factory ───────────────────────────────────────────────

    /// <summary>
    /// Create a DroppedItemData snapshot from an ItemModel at a given world position.
    /// dropId, roomName, droppedAt, expireAt are NOT set here — Master sets them.
    /// </summary>
    public static DroppedItemData FromItemModel(ItemModel item, float posX, float posY)
    {
        if (item == null) return null;

        return new DroppedItemData
        {
            itemId       = item.ItemId,
            itemName     = item.ItemName,
            itemType     = item.ItemType,
            itemCategory = item.ItemCategory,
            quality      = item.Quality,
            quantity      = item.Quantity,
            iconUrl      = item.ItemData?.iconUrl,
            isStackable  = item.IsStackable,
            worldX       = posX,
            worldY       = posY
        };
    }
}
